-- ======================================================================
--
-- audit.sql
--
-- Read-only audit of the integer columns the servers bind as 32-bit
-- values. Run it as the owner of each schema (the game schema and the
-- login schema) before upgrading to servers that bind these columns as
-- DB::BindableInt32 / DB::BindableUint32. It reports:
--
--   - values outside [-2147483648, 2147483647]; loading such a row now
--     fails with ORA-01455 instead of reaching the server truncated;
--   - fractional values, which a 32-bit binding cannot represent;
--   - for columns persisted from a narrower member (int8, uint8, ...),
--     values outside that member's range, which the object encoder
--     refuses. NULLs there are listed as INFO: they load as the value a
--     new object gets, with a warning.
--   - for columns a hand-written loader narrows further (LOAD_RANGE in the
--     .tab file), values outside that range, which fail the load.
--   - as INFO, NULLs in columns whose loader gives a NULL a value
--     (NULL_LOADS_AS in the .tab file), with the value it loads.
--
-- The column list is generated by make_audit.pl from the schema .tab files;
-- do not edit it by hand. Invoke as @audit.sql game (or login, sp-character).
-- Every listed column for the selected schema must exist. The script only reads.
--
-- ======================================================================

whenever oserror exit failure rollback
whenever sqlerror exit failure rollback
set serveroutput on size unlimited
set linesize 250
set trimout on
set feedback off
set verify off

declare
	schema_kind constant varchar2(32) := lower('&1');
	all_entries sys.odcivarchar2list := sys.odcivarchar2list(
		'game.ACCOUNT_MAP.PARENT_ID.uint32',
		'game.ACCOUNT_MAP.CHILD_ID.uint32',
		'game.ACCOUNTS.STATION_ID.uint32',
		'game.ACCOUNTS.NUM_LOTS.int32',
		'game.ACCOUNTS.MAX_LOTS_ADJUSTMENT.int32',
		'game.ARMOR.LAYER.int32',
		'game.ARMOR.EFFECTIVENESS.int32',
		'game.ARMOR.INTEGRITY.int32',
		'game.ARMOR.ENCUMBERANCE_0.int32',
		'game.ARMOR.ENCUMBERANCE_1.int32',
		'game.ARMOR.ENCUMBERANCE_2.int32',
		'game.ARMOR.ENCUMBERANCE_3.int32',
		'game.ARMOR.ENCUMBERANCE_4.int32',
		'game.ARMOR.ENCUMBERANCE_5.int32',
		'game.ARMOR.ENCUMBERANCE_6.int32',
		'game.ARMOR.ENCUMBERANCE_7.int32',
		'game.ARMOR.ENCUMBERANCE_8.int32',
		'game.AUCTION_LOCATIONS.SALES_TAX.int32',
		'game.AUCTION_LOCATIONS.EMPTY_DATE.int32',
		'game.AUCTION_LOCATIONS.LAST_ACCESS_DATE.int32',
		'game.AUCTION_LOCATIONS.INACTIVE_DATE.int32',
		'game.AUCTION_LOCATIONS.STATUS.int32',
		'game.AUCTION_LOCATIONS.ENTRANCE_CHARGE.int32',
		'game.AUTOMATED_QUERIES.ID.int32',
		'game.AUTOMATED_QUERIES.RUN_SERIAL.int32',
		'game.AUTOMATED_QUERIES.EXEC_ORDER.int32',
		'game.BATTLEFIELD_PARTICIPANTS.FACTION_ID.uint32',
		'game.BUILDING_OBJECTS.MAINTENANCE_COST.int32',
		'game.BUILDING_OBJECTS.CITY_ID.int32',
		'game.CELL_OBJECTS.CELL_NUMBER.int32',
		'game.CLOCK.LAST_SAVE_TIME.int32',
		'game.CREATURE_OBJECTS.POSTURE.int32',
		'game.CREATURE_OBJECTS.SHOCK_WOUNDS.int32',
		'game.CREATURE_OBJECTS.RANK.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_0.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_1.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_2.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_3.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_4.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_5.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_6.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_7.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_8.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_9.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_10.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_11.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_12.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_13.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_14.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_15.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_16.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_17.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_18.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_19.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_20.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_21.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_22.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_23.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_24.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_25.int32',
		'game.CREATURE_OBJECTS.ATTRIBUTE_26.int32',
		'game.CREATURE_OBJECTS.POSTURE.int8',
		'game.CREATURE_OBJECTS.RANK.uint8',
		'game.DELETE_REASONS.REASON_CODE.int32',
		'game.EXPERIENCE_POINTS.POINTS.int32',
		'game.GCW_LEADERBOARD.PERIOD.int32',
		'game.GCW_LEADERBOARD.PERIOD_END.int32',
		'game.GCW_LEADERBOARD.LAST_UPDATED.int32',
		'game.HARVESTER_INSTALLATION_OBJECTS.MAX_EXTRACTION_RATE.int32',
		'game.HARVESTER_INSTALLATION_OBJECTS.MAX_HOPPER_AMOUNT.int32',
		'game.INSTALLATION_OBJECTS.INSTALLATION_TYPE.int32',
		'game.INTANGIBLE_OBJECTS.COUNT.int32',
		'game.LOADBEACON_SERVER_MAP.SERVER_ID.int32',
		'game.LOADBEACON_SERVER_MAP.SECONDARY_SERVER_ID.int32',
		'game.LOCATION_LISTS.LIST_ID.uint32',
		'game.LOCATION_LISTS.SEQUENCE_NUMBER.uint32',
		'game.MANF_SCHEMATIC_OBJECTS.ITEMS_PER_CONTAINER.int32',
		'game.MANF_SCHEMATIC_OBJECTS.DRAFT_SCHEMATIC.int32',
		'game.MARKET_AUCTION_BIDS.BID.int32',
		'game.MARKET_AUCTION_BIDS.MAX_PROXY_BID.int32',
		'game.MARKET_AUCTIONS.MIN_BID.int32',
		'game.MARKET_AUCTIONS.BUY_NOW_PRICE.int32',
		'game.MARKET_AUCTIONS.AUCTION_TIMER.int32',
		'game.MARKET_AUCTIONS.CATEGORY.int32',
		'game.MARKET_AUCTIONS.ITEM_TIMER.int32',
		'game.MARKET_AUCTIONS.ACTIVE.int32',
		'game.MARKET_AUCTIONS.ITEM_SIZE.int32',
		'game.MARKET_AUCTIONS.OBJECT_TEMPLATE_ID.uint32',
		'game.MESSAGES.CALL_TIME.uint32',
		'game.MESSAGES.DELIVERY_TYPE.int32',
		'game.MISSION_OBJECTS.DIFFICULTY.int32',
		'game.MISSION_OBJECTS.END_SCENE.uint32',
		'game.MISSION_OBJECTS.REWARD.int32',
		'game.MISSION_OBJECTS.START_SCENE.uint32',
		'game.MISSION_OBJECTS.STATUS.int32',
		'game.MISSION_OBJECTS.MISSION_TYPE.uint32',
		'game.MISSION_OBJECTS.TARGET_APPEARANCE.uint32',
		'game.OBJECT_LIST.CONTAINER_LEVEL.int32',
		'game.OBJECT_TEMPLATES.ID.uint32',
		'game.OBJECT_VARIABLE_NAMES.ID.int32',
		'game.OBJECT_VARIABLES.NAME_ID.int32',
		'game.OBJECT_VARIABLES.TYPE.int32',
		'game.OBJECT_VARIABLES.DETACHED.int32',
		'game.OBJECTS.NODE_X.int32',
		'game.OBJECTS.NODE_Y.int32',
		'game.OBJECTS.NODE_Z.int32',
		'game.OBJECTS.TYPE_ID.uint32',
		'game.OBJECTS.CONTROLLER_TYPE.int32',
		'game.OBJECTS.DELETED.int32',
		'game.OBJECTS.VOLUME.int32',
		'game.OBJECTS.SLOT_ARRANGEMENT.int32',
		'game.OBJECTS.CACHE_VERSION.int32',
		'game.OBJECTS.CASH_BALANCE.int32',
		'game.OBJECTS.BANK_BALANCE.int32',
		'game.OBJECTS.OBJECT_TEMPLATE_ID.uint32',
		'game.OBJECTS.STATIC_ITEM_VERSION.int32',
		'game.OBJECTS.CONVERSION_ID.int32',
		'game.OBJECTS.OBJVAR_0_TYPE.int32',
		'game.OBJECTS.OBJVAR_1_TYPE.int32',
		'game.OBJECTS.OBJVAR_2_TYPE.int32',
		'game.OBJECTS.OBJVAR_3_TYPE.int32',
		'game.OBJECTS.OBJVAR_4_TYPE.int32',
		'game.OBJECTS.OBJVAR_5_TYPE.int32',
		'game.OBJECTS.OBJVAR_6_TYPE.int32',
		'game.OBJECTS.OBJVAR_7_TYPE.int32',
		'game.OBJECTS.OBJVAR_8_TYPE.int32',
		'game.OBJECTS.OBJVAR_9_TYPE.int32',
		'game.OBJECTS.OBJVAR_10_TYPE.int32',
		'game.OBJECTS.OBJVAR_11_TYPE.int32',
		'game.OBJECTS.OBJVAR_12_TYPE.int32',
		'game.OBJECTS.OBJVAR_13_TYPE.int32',
		'game.OBJECTS.OBJVAR_14_TYPE.int32',
		'game.OBJECTS.OBJVAR_15_TYPE.int32',
		'game.OBJECTS.OBJVAR_16_TYPE.int32',
		'game.OBJECTS.OBJVAR_17_TYPE.int32',
		'game.OBJECTS.OBJVAR_18_TYPE.int32',
		'game.OBJECTS.OBJVAR_19_TYPE.int32',
		'game.PLAYER_OBJECTS.STATION_ID.uint32',
		'game.PLAYER_OBJECTS.BORN_DATE.int32',
		'game.PLAYER_OBJECTS.PLAYED_TIME.int32',
		'game.PLAYER_OBJECTS.FORCE_POWER.int32',
		'game.PLAYER_OBJECTS.MAX_FORCE_POWER.int32',
		'game.PLAYER_OBJECTS.NUM_LOTS.int32',
		'game.PLAYER_OBJECTS.CURRENT_QUEST.uint32',
		'game.PLAYER_OBJECTS.ROLE_ICON_CHOICE.int32',
		'game.PLAYER_OBJECTS.CURRENT_GCW_POINTS.int32',
		'game.PLAYER_OBJECTS.CURRENT_GCW_RATING.int32',
		'game.PLAYER_OBJECTS.CURRENT_PVP_KILLS.int32',
		'game.PLAYER_OBJECTS.MAX_GCW_IMPERIAL_RATING.int32',
		'game.PLAYER_OBJECTS.MAX_GCW_REBEL_RATING.int32',
		'game.PLAYER_OBJECTS.LIFETIME_PVP_KILLS.int32',
		'game.PLAYER_OBJECTS.NEXT_GCW_RATING_CALC_TIME.int32',
		'game.PLAYER_QUEST_OBJECTS.TOTAL_TASKS.int32',
		'game.PLAYER_QUEST_OBJECTS.DIFFICULTY.int32',
		'game.PLAYERS.STATION_ID.uint32',
		'game.PROPERTY_LISTS.LIST_ID.int32',
		'game.RESOURCE_CONTAINER_OBJECTS.QUANTITY.int32',
		'game.RESOURCE_TYPES.DEPLETED_TIMESTAMP.uint32',
		'game.SCRIPTS.SEQUENCE_NO.int32',
		'game.SCRIPTS.DETACHED.int32',
		'game.SHIP_OBJECTS.CHASSIS_TYPE.uint32',
		'game.SHIP_OBJECTS.CARGO_HOLD_CONTENTS_MAXIMUM.int32',
		'game.SHIP_OBJECTS.CARGO_HOLD_CONTENTS_CURRENT.int32',
		'game.TANGIBLE_OBJECTS.MAX_HIT_POINTS.int32',
		'game.TANGIBLE_OBJECTS.INTEREST_RADIUS.int32',
		'game.TANGIBLE_OBJECTS.PVP_TYPE.int32',
		'game.TANGIBLE_OBJECTS.PVP_FACTION.uint32',
		'game.TANGIBLE_OBJECTS.DAMAGE_TAKEN.int32',
		'game.TANGIBLE_OBJECTS.COUNT.int32',
		'game.TANGIBLE_OBJECTS.CONDITION.int32',
		'game.TANGIBLE_OBJECTS.SOURCE_DRAFT_SCHEMATIC.uint32',
		'game.TEMP_CHARACTERS.TRANSACTION_TYPE.int32',
		'game.TEMP_CHARACTERS.STATION_ID.uint32',
		'game.VEHICLE_OBJECTS.BOGUS.int32',
		'game.WAYPOINTS.APPEARANCE_NAME_CRC.uint32',
		'game.WAYPOINTS.LOCATION_SCENE.uint32',
		'game.WAYPOINTS.COLOR.r:0:255',
		'game.WAYPOINTS.COLOR.int32',
		'game.WEAPON_OBJECTS.MIN_DAMAGE.int32',
		'game.WEAPON_OBJECTS.MAX_DAMAGE.int32',
		'game.WEAPON_OBJECTS.DAMAGE_TYPE.int32',
		'game.WEAPON_OBJECTS.ELEMENTAL_TYPE.int32',
		'game.WEAPON_OBJECTS.ELEMENTAL_VALUE.int32',
		'game.WEAPON_OBJECTS.ACCURACY.int32',
		'game.WEAPON_OBJECTS.ATTACK_COST.int32',
		'login.ACCOUNT_EXTRACT.USER_ID.int32',
		'login.ACCOUNT_EXTRACT.SUBSCRIPTION_ID.int32',
		'login.ACCOUNT_EXTRACT.PLAN_ID.int32',
		'login.ACCOUNT_EXTRACT.STATUS.int32',
		'login.ACCOUNT_EXTRACT.TOTAL_ENTITLED_TIME.int32',
		'login.ACCOUNT_INFO.STATION_ID.uint32',
		'login.ACCOUNT_REWARD_EVENTS.STATION_ID.uint32',
		'login.ACCOUNT_REWARD_EVENTS.CLUSTER_ID.uint32',
		'login.ACCOUNT_REWARD_ITEMS.STATION_ID.uint32',
		'login.ACCOUNT_REWARD_ITEMS.CLUSTER_ID.uint32',
		'login.CHARACTER_TYPES.ID.int32',
		'login.CLUSTER_LIST.ID.uint32',
		'login.CLUSTER_LIST.NUM_CHARACTERS.int32',
		'login.CLUSTER_LIST.PORT.r:0:65535',
		'login.CLUSTER_LIST.PORT.int32',
		'login.CLUSTER_LIST.GROUP_ID.int32',
		'login.CLUSTER_LIST.ONLINE_PLAYER_LIMIT.int32',
		'login.CLUSTER_LIST.ONLINE_FREE_TRIAL_LIMIT.int32',
		'login.CLUSTER_LIST.ONLINE_TUTORIAL_LIMIT.int32',
		'login.DEFAULT_CHAR_LIMITS.ACCOUNT_LIMIT.int32',
		'login.DEFAULT_CHAR_LIMITS.CLUSTER_LIMIT.int32',
		'login.DEFAULT_CHARACTER_SLOTS.CHARACTER_TYPE_ID.r:0:3',
		'login.DEFAULT_CHARACTER_SLOTS.CHARACTER_TYPE_ID.int32',
		'login.DEFAULT_CHARACTER_SLOTS.NUM_SLOTS.int32',
		'login.EXTRA_CHARACTER_SLOTS.STATION_ID.uint32',
		'login.EXTRA_CHARACTER_SLOTS.CLUSTER_ID.uint32',
		'login.EXTRA_CHARACTER_SLOTS.CHARACTER_TYPE_ID.int32',
		'login.EXTRA_CHARACTER_SLOTS.NUM_EXTRA_SLOTS.int32',
		'login.FEATURE_ID_TRANSACTIONS.STATION_ID.uint32',
		'login.FEATURE_ID_TRANSACTIONS.CLUSTER_ID.uint32',
		'login.FEATURE_ID_TRANSACTIONS.COUNT.int32',
		'login.PURGE_ACCOUNTS.STATION_ID.uint32',
		'login.PURGE_ACCOUNTS.PURGE_PHASE.int32',
		'login.PURGE_PHASES.ID.int32',
		'login.STATION_ID_SCHEME.ID.int32',
		'login.STATUSES.ID.int32',
		'login.SWG_CHARACTERS.STATION_ID.uint32',
		'login.SWG_CHARACTERS.CLUSTER_ID.uint32',
		'login.SWG_CHARACTERS.CHARACTER_TYPE.int32',
		'login.SWG_CHARACTERS.TEMPLATE_ID.uint32',
		'sp-character.CHARACTER_PROFILE.STATION_ID.uint32',
		'sp-character.CHARACTER_PROFILE.NUM_LOTS.int32'
	);

	-- columns whose loader gives a NULL a value (NULL_LOADS_AS in the .tab files)
	null_defaults sys.odcivarchar2list := sys.odcivarchar2list(
		'game.MESSAGES.CALL_TIME|0',
		'game.WAYPOINTS.COLOR|Waypoint::Blue'
	);

	entries     sys.odcivarchar2list := sys.odcivarchar2list();
	type name_list is table of varchar2(128);
	cols        name_list := name_list();
	kinds       name_list := name_list();
	tab         varchar2(128);
	sql_text    varchar2(32767);
	cursor_id   integer := null;
	ignore      integer;
	row_count   number;
	value       number;
	checked     integer := 0;
	missing     integer := 0;
	problems    integer := 0;
	infos       integer := 0;
	tables_seen integer := 0;
	i           integer;
	lo          number;
	hi          number;
	field       integer;

	procedure bounds(kind varchar2, lo out number, hi out number) is
	begin
		if kind like 'r:%' then
			lo := to_number(substr(kind, 3, instr(kind, ':', 3) - 3));
			hi := to_number(substr(kind, instr(kind, ':', 3) + 1));
		elsif kind in ('int32', 'uint32') then lo := -2147483648; hi := 2147483647;
		elsif kind = 'int16' then lo := -32768; hi := 32767;
		elsif kind = 'uint16' then lo := 0; hi := 65535;
		elsif kind = 'int8' then lo := -128; hi := 127;
		elsif kind = 'uint8' then lo := 0; hi := 255;
		else raise_application_error(-20001, 'unknown kind ' || kind);
		end if;
	end;

	-- a persisted member narrower than its column (int8, uint8, ...)
	function narrow(kind varchar2) return boolean is
	begin
		return kind not in ('int32', 'uint32') and kind not like 'r:%';
	end;

	function table_of(entry varchar2) return varchar2 is
	begin
		return substr(entry, 1, instr(entry, '.') - 1);
	end;

	procedure problem(text varchar2) is
	begin
		problems := problems + 1;
		dbms_output.put_line('PROBLEM ' || text);
	end;

begin
	if schema_kind not in ('game', 'login', 'sp-character') then
		raise_application_error(-20002, 'Expected schema argument: game, login, or sp-character');
	end if;
	for k in 1 .. all_entries.count loop
		if substr(all_entries(k), 1, instr(all_entries(k), '.') - 1) = schema_kind then
			entries.extend;
			entries(entries.count) := substr(all_entries(k), instr(all_entries(k), '.') + 1);
		end if;
	end loop;
	if entries.count = 0 then
		raise_application_error(-20003, 'No audit contract for selected schema');
	end if;
	dbms_output.put_line('Auditing ' || schema_kind || ' schema owned by ' || user);
	i := 1;
	while i <= entries.count loop
		tab := table_of(entries(i));
		cols.delete;
		kinds.delete;
		while i <= entries.count and table_of(entries(i)) = tab loop
			declare
				rest varchar2(256) := substr(entries(i), instr(entries(i), '.') + 1);
				col  varchar2(128) := substr(rest, 1, instr(rest, '.') - 1);
				kind varchar2(64)  := substr(rest, instr(rest, '.') + 1);
				n    integer;
			begin
				select count(*) into n from user_tab_columns where table_name = tab and column_name = col;
				if n = 0 then
					missing := missing + 1;
					problem('missing required column ' || tab || '.' || col);
				else
					cols.extend; cols(cols.count) := col;
					kinds.extend; kinds(kinds.count) := kind;
				end if;
			end;
			i := i + 1;
		end loop;

		if cols.count > 0 then
			tables_seen := tables_seen + 1;
			sql_text := 'select count(*)';
			for c in 1 .. cols.count loop
				bounds(kinds(c), lo, hi);
				sql_text := sql_text
					|| ', sum(case when "' || cols(c) || '" < ' || lo || ' or "' || cols(c) || '" > ' || hi || ' then 1 else 0 end)'
					|| ', sum(case when "' || cols(c) || '" <> trunc("' || cols(c) || '") then 1 else 0 end)'
					|| ', min("' || cols(c) || '"), max("' || cols(c) || '")'
					|| ', sum(case when "' || cols(c) || '" is null then 1 else 0 end)';
			end loop;
			sql_text := sql_text || ' from "' || tab || '"';

			cursor_id := dbms_sql.open_cursor;
			dbms_sql.parse(cursor_id, sql_text, dbms_sql.native);
			for f in 1 .. 1 + 5 * cols.count loop
				dbms_sql.define_column(cursor_id, f, value);
			end loop;
			ignore := dbms_sql.execute(cursor_id);
			ignore := dbms_sql.fetch_rows(cursor_id);
			dbms_sql.column_value(cursor_id, 1, row_count);

			for c in 1 .. cols.count loop
				checked := checked + 1;
				bounds(kinds(c), lo, hi);
				field := 2 + 5 * (c - 1);
				declare
					out_of_range number; fractional number; min_v number; max_v number; nulls number;
				begin
					dbms_sql.column_value(cursor_id, field, out_of_range);
					dbms_sql.column_value(cursor_id, field + 1, fractional);
					dbms_sql.column_value(cursor_id, field + 2, min_v);
					dbms_sql.column_value(cursor_id, field + 3, max_v);
					dbms_sql.column_value(cursor_id, field + 4, nulls);
					if nvl(out_of_range, 0) > 0 then
						problem(tab || '.' || cols(c) || ' (' || kinds(c) || '): ' || out_of_range
							|| ' row(s) outside [' || lo || ', ' || hi || '], min ' || min_v || ', max ' || max_v);
					end if;
					if nvl(fractional, 0) > 0 then
						problem(tab || '.' || cols(c) || ' (' || kinds(c) || '): ' || fractional || ' row(s) with a fractional value');
					end if;
					if narrow(kinds(c)) and nvl(nulls, 0) > 0 then
						infos := infos + 1;
						dbms_output.put_line('INFO ' || tab || '.' || cols(c) || ' (' || kinds(c) || '): ' || nulls
							|| ' NULL row(s) will load as the new-object default, with a warning');
					end if;
				end;
			end loop;
			dbms_sql.close_cursor(cursor_id);
		end if;
	end loop;

	-- NULLs a loader replaces with a value: informational
	for k in 1 .. null_defaults.count loop
		declare
			spec varchar2(512) := substr(null_defaults(k), instr(null_defaults(k), '.') + 1);
			col_full varchar2(256) := substr(spec, 1, instr(spec, '|') - 1);
			what varchar2(256) := substr(spec, instr(spec, '|') + 1);
			t varchar2(128) := substr(col_full, 1, instr(col_full, '.') - 1);
			c varchar2(128) := substr(col_full, instr(col_full, '.') + 1);
			n integer;
			nulls number;
		begin
			select count(*) into n from user_tab_columns where table_name = t and column_name = c;
			if substr(null_defaults(k), 1, instr(null_defaults(k), '.') - 1) = schema_kind and n > 0 then
				execute immediate 'select count(*) from "' || t || '" where "' || c || '" is null' into nulls;
				if nulls > 0 then
					infos := infos + 1;
					dbms_output.put_line('INFO ' || col_full || ': ' || nulls || ' NULL row(s) will load as ' || what || ', with a warning');
				end if;
			end if;
		end;
	end loop;

	dbms_output.put_line('int32 audit: ' || checked || ' column(s) in ' || tables_seen || ' table(s) checked, '
		|| missing || ' required column check(s) missing, ' || problems || ' problem(s), ' || infos || ' informational');
	if problems = 0 then
		dbms_output.put_line('RESULT: CLEAN (' || schema_kind || ', complete integer-column coverage)');
	else
		dbms_output.put_line('RESULT: FAILED: ' || problems || ' PROBLEM(S). Correct schema coverage and data before upgrading; nothing was changed.');
		raise_application_error(-20004, 'Integer audit failed: ' || problems || ' problem(s)');
	end if;
exception
	when others then
		if cursor_id is not null and dbms_sql.is_open(cursor_id) then
			dbms_sql.close_cursor(cursor_id);
		end if;
		raise;
end;
/
